### PR TITLE
Fix crashes in ColumnsReview64 by backporting childCount getter for UIA from NVDA 2020.3

### PR DESCRIPTION
**Pull request by lukaszgo1**
As discussed in https://github.com/nvaccess/nvda/issues/11444 Python 3 versions of NVDA can sometimes crash with recursion error when `childCount` is accessed in `initOverlayClass`. For ColumnsReview this was causing crashes in Windows 10 task manager among other places. Previously columns Review has been simply disabled in  task manager. This PR backports improved implementation of ``_get_childCount` from NVDA 2020.3 - it is used only  for affected versions.

### CODE REVIEW

**Comment by ABuffEr** [comment]
Hi @lukaszgo1 ,
first, thanks again for your continuated contribution on this add-on.
Then, I merged the PR and tested with Win10 task manager (that I not know very well). At this point, correct me if I'm wrong:
1) code uses provided implementation until 2020.3, core implementation otherwise (in other words, no refactoring needed for 2020.4 and later);
2) the add-on never chrashes in task manager, but an additional work is required to support the particular column organization in task manager listview (in other words, no information is available via add-on gestures).
Right?

**Comment by lukaszgo1** [comment]
@ABuffEr wrote:
> first, thanks again for your continuated contribution on this add-on.

Thanks for the add-on :-) I haven't realized how useful it is until I've started using it so contributing is the least I can do to say thanks.

>     1. code uses provided implementation until 2020.3, core implementation otherwise (in other words, no refactoring needed for 2020.4 and later);

The core implementation is also used for Python 2 versions of NVDA because for whatever reason the crash was not occurring with them. Indeed there is no refactoring needed going forward.

>     2. the add-on never chrashes in task manager, but an additional work is required to support the particular column organization in task manager listview (in other words, no information is available via add-on gestures).
>        Right?

From my short testing (I'm still on Windows 7 so I've just tested quickly on a VM) this seems correct.

**Comment by ABuffEr** [comment]
Hi @lukaszgo1 ,
can you review this code according to recent changes in master?
I commented it in CRList64 class (the new implementation, at list level, for UIA list, limited to "UIItemsView" cachedClassName), and I'd prefer to be you to test and modify it :)

**Comment by lukaszgo1** [comment]
@ABuffEr Thanks for a ping. I'll look at your latest changes ASAP.

**Pull request merged**
