### PR TITLE
Add missing comments for translators

### PR DESCRIPTION
**Pull request by lukaszgo1**
Currently checks on PR's are failing due to missing translators comments. This PR adds missing comments and refactors slightly the neighboring code where necessary.

### CODE REVIEW

**Comment by ABuffEr** [comment]
Hi @lukaszgo1 ,
thanks, as usual. I delayed merge to have time for analyzing diff.
I'm working on Outlook support, as written on nvda-addons list. I hope to finish in this week, then I'll merge #15, that seems a bit more extended refactoring.
In the future, I'm thinking to separate each list class from __init__, to better readability and development of new classes.

**Comment by lukaszgo1** [comment]
> thanks, as usual. I delayed merge to have time for analyzing diff.

No problem - there was no rush and merging code which you won't understand is pretty bad idea.


> In the future, I'm thinking to separate each list class from **init**, to better readability and development of new classes.

I agree that is reasonable direction to take though it would  require some consideration as even with #15 merged there is still some global state making such moves difficult. 
Would you be interested in accepting PR's in that direction?

**Comment by ABuffEr** [comment]
> > In the future, I'm thinking to separate each list class from **init**, to better readability and development of new classes.
> I agree that is reasonable direction to take though it would require some consideration as even with #15 merged there is still some global state making such moves difficult. Would you be interested in accepting PR's in that direction?


Hi,
absolutely yes, especially considering you have a better overview of the code after #15, that I'll see in next days.

Meantime, I created a new branch outlookSupport (almost complete) based on b20210910 tag, that should make easier to merge changes after that commit.

**Comment by lukaszgo1** [comment]
> Hi, absolutely yes, especially considering you have a better overview of the code after #15, that I'll see in next days.

Cannot promise anything fast, but I'll have this direction in mind when writing some further fixes / changes eventually.
> 
> Meantime, I created a new branch outlookSupport (almost complete) based on b20210910 tag, that should make easier to merge changes after that commit.



I've left some review comments on that branch - hope this is okay? Note that I had no way to test this code live as my version of Outlook is pretty ancient.

**Pull request merged**
